# Generated by Django 4.1 on 2022-09-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_canvas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
