# Generated by Django 4.1 on 2022-09-14 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to=settings.AUTH_USER_MODEL),
        ),
    ]
